name: Python Lint
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '22 3 * * 2'  # please pick a different time
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        linter: [flake8, pylint, ruff, mypy, pytype, pyright, fixit]
      fail-fast: false

    steps:
      - name: Python Lint
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: ${{ matrix.linter }}
          python-version: 3.10
