name: Python Lint Workflow
on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        linter: ['flake8', 'pylint', 'ruff', 'mypy', 'pytype', 'pyright', 'fixit']
        python-version: ['3.10']
        os: [windows-latest]
      fail-fast: false

    steps:
      # install dependencies for all linters, then run the linter, so we don't get import failures when the linters scan the code
      # upgrade pip, so that we can install flake8_sarif_formatter properly from the git repo
      - uses: actions/checkout@v4
      - name: Install pip dependencies
        run: |
          python3 -mpip install -q --upgrade pip
          python3 -mpip install -q flake8 pylint ruff mypy pytype pyright fixit pyre-check
          python3 -mpip install -q flake8-sarif-formatter
      - name: Run Python Lint
        uses: advanced-security/python-lint-code-scanning-action@main
        with:
          linter: ${{ matrix.linter }}
          python-version: ${{ matrix.python-version }}